[package]
name = "uzh-mnf-phd"
version = "0.1.0"
entrypoint = "src/lib.typ"
authors = [
	"Emanuel Kopp <https://github.com/emanuel-kopp/>"
]
license = "MIT"
description = "Unofficial template for PhD Thesis at MNF at the University of Zurich"
# homepage = ""
# repository = ""
keywords = ["Dissertation", "phd", "UZH", "MNF", "thesis"]
categories = ["Thesis"]
disciplines = ["natural-sciences"]
compiler = "0.12.0"
# exclude = []

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"

# [tool.mytool]
# foo = "bar"
